---
title: "HBV 2023"
output: html_document
date: "2025-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RCurl)
library(tidyverse)
library(XML)
library(xml2)
library(rvest)
library(readxl)
library(openxlsx)
```


```{r}
path <- paste0("../xlsx/oral/", list.files("../xlsx/oral"))


  df_ex <- read.xlsx(path, startRow = 3,
                 fillMergedCells = FALSE) 
  
```


# save oral

```{r}
get_data_oral <- function(xlsx_path){
  
  # read excel sheet
  df <- read.xlsx(xlsx_path, startRow = 3,
                 fillMergedCells = FALSE,
                 cols = 1:9) 
  
  # get sheet name
  sheet_name <- getSheetNames(xlsx_path)
  
  
  # clean colnames
  colnames(df)[1:9] <- c("CLASS_code", "CLASS_name",
                       "DRUG_code", "DRUG_name", "UNIT",
                       "COST_code", "COST_per",
                       "GEN", "TOTAL")
  
  # add file name
  df <- df %>% mutate(FILE_ori = xlsx_path) %>%
    mutate(FILE = str_extract(FILE_ori, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    relocate(FILE, .before = "CLASS_code")

   # add sheet name and type
  df <- df %>% mutate(SHEET_jp = sheet_name) %>%
    mutate(TYPE = case_when(str_detect(SHEET_jp, "内服")　~ "oral",
                            str_detect(SHEET_jp, "外用") ~ "ext",
                            str_detect(SHEET_jp, "注射") ~ "inj")) %>%
    relocate(TYPE, .after = "FILE")
    
  # add sheet
  df <- df %>%
    mutate(SHEET = case_when(str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院内")~ "outpt_inpr",
                             str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院外")~ "outpt_outpr",
                             str_detect(SHEET_jp, "入院") ~ "inpt")) %>%
    relocate(SHEET, .after = "FILE")

  # add sheet
  df <- df %>% select(!FILE_ori)

   
  # fill empty cells in CLASS columns
  df <- df %>%
    tidyr::fill(starts_with("CLASS_"), .direction = "down")
  
  
    # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # create function for getting year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow = 1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  # get df for year
  df_year <- get_year(xlsx_path, sheet_name)
    
  df <- df %>% left_join(df_year, by = join_by(FILE))
  
  # convert everything to character for now
  df <- df %>% mutate(across(everything(), as.character))
  
  return(df)

  }
```


```{r}
paste0("../xlsx/oral/", list.files("../xlsx/oral")) %>%
  get_data_oral() 
```


```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (oral ext inj)
# y is the individual folder

save_df_oral <- function(x){
  xlsx <- list.files(paste0("../xlsx/", x))

    from <- paste0("../xlsx/", x, "/", xlsx)
  
  df <- map(from, get_data_oral) %>% list_rbind()
}
```


```{r}
save_df_oral("oral") %>% saveRDS("../rds/df_oral.RDS")
```
