---
title: "HBV 2023"
output: html_document
date: "2025-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RCurl)
library(tidyverse)
library(XML)
library(xml2)
library(rvest)
library(readxl)
library(openxlsx)
```



# 3-9

```{r}
get_data_inj <- function(xlsx_path){
  
  sheet_name <- getSheetNames(xlsx_path)
  
  # read excel sheet
  list_df <- map2(xlsx_path,
                  sheet_name,
                  function(x, y) read.xlsx(x,
                                           sheet = y,
                                           startRow = 3,
                                           fillMergedCells = FALSE,
                                           cols = 1:9
                                           )) 


  #paset here
  new_colnames <- c("CLASS_code", "CLASS_name",
                       "DRUG_code", "DRUG_name", "UNIT",
                       "COST_code", "COST_per",
                       "GEN", "TOTAL")
  
  
  list_df <- map(list_df,
                 function(x){
                   colnames(x) <- new_colnames
                   return(x)})
  
  # add file name
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     mutate(FILE = xlsx_path) %>%
                     mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
                     relocate(FILE, .before = "CLASS_code")  
                 })

   # add sheet name and do one hot coding for sheet
  # "注射薬 外来 (院内)" "注射薬 外来 (院外)" "注射薬 入院"  
  list_df <- map2(list_df, sheet_name,
                 function(x, y){
                   x %>% 
                     mutate(SHEET_jp = y) %>%
    mutate(TYPE = case_when(str_detect(SHEET_jp, "内服")　~ "oral",
                            str_detect(SHEET_jp, "外用") ~ "ext",
                            str_detect(SHEET_jp, "注射") ~ "inj")) %>%
    relocate(TYPE, .after = "FILE")
                   })
  
  # add sheet
  list_df <- map(list_df,
                 function(x){
                   x %>%
    mutate(SHEET = case_when(str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院内")~ "outpt_inpr",
                             str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院外")~ "outpt_outpr",
                             str_detect(SHEET_jp, "入院") ~ "inpt")) }) 
  
  # fill missing cells
  
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     tidyr::fill(starts_with("CLASS_"), .direction = "down") %>%
                     mutate(across(everything(), as.character))
                 })
  
    # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # get year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow =1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  list_year <- map2(xlsx_path,
                     sheet_name, get_year)
    
  list_df <- map2(list_df, list_year, function(x, y){
    x %>% left_join(y, by = join_by(FILE == FILE))
  })
  
  
  # colnames
  df <- list_df %>% list_rbind()
  
  return(df)

  }
```


```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (oral ext inj)
# y is the individual folder (dem, prf)

save_df_inj <- function(x){
  xlsx <- list.files(paste0("../xlsx/", x ))
  
    from <- paste0("../xlsx/", x, "/", xlsx)
  
  df <- map(from, get_data_inj) %>% list_rbind()
}
```


```{r}
save_df_inj("inject") %>% saveRDS("../rds/df_inject.RDS")
```


```{r}
df_inj <- readRDS("../rds/df_inject.RDS")
```


```{r}
df_inj %>% count(SHEET_jp)
```