---
title: "HBV 2023"
output: html_document
date: "2025-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RCurl)
library(tidyverse)
library(XML)
library(xml2)
library(rvest)
library(readxl)
library(openxlsx)

```




# read first two files

```{r}
get_data_surg_reg <- function(xlsx_path){
  
  sheet_name <- getSheetNames(xlsx_path)
  
  sheet_name <- sheet_name[!str_detect(sheet_name, "加算")]
  
  # read excel sheet
  list_df <- map2(xlsx_path,
                  sheet_name,
                  function(x, y) read.xlsx(x,
                                           sheet = y,
                                           startRow = 3,
                                           fillMergedCells = FALSE,
                                           cols = 1:7)) 
  
  # clean colnames
  new_colnames <- c("ORGAN", "CLASS_code", "CLASS_name",
                       "PRO_code", "PRO_name",
                       "POINT", "TOTAL")

  list_df <- map(list_df,
                 function(x){
                   colnames(x) <- new_colnames
                   return(x)})
  
  # add file name

  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     mutate(FILE = xlsx_path) %>%
                     mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
                     relocate(FILE, .before = "CLASS_code")  
                 })

  # add sheet name and do one hot coding for sheet
  # "全体"
  # "外来"         "外来（加算）" "入院"         "入院（加算）"
  list_df <- map2(list_df, sheet_name,
                 function(x, y){
                   x %>% 
                     mutate(SHEET_jp = y) %>%
                         mutate(SHEET = case_when(
                           str_detect(SHEET_jp, "全体") ~ "all",
                           str_detect(SHEET_jp, "外来")　&
                             !str_detect(SHEET_jp, "加算")~ "out",
                           str_detect(SHEET_jp, "外来")　&
                             str_detect(SHEET_jp, "加算")~ "out_add",
                           str_detect(SHEET_jp, "入院") &
                             !str_detect(SHEET_jp, "加算") ~ "in",
                           str_detect(SHEET_jp, "入院") &
                             str_detect(SHEET_jp, "加算") ~ "in_add"))    %>%
                     relocate(SHEET, .after = "FILE")
                   })
  
  # fill missing cells
  
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     tidyr::fill(c(ORGAN , starts_with("CLASS_")),
                                 .direction = "down") %>%
                     mutate(across(everything(), as.character))
                 })
  
     # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # get year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow =1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  list_year <- map2(xlsx_path,
                     sheet_name, get_year)
    
  list_df <- map2(list_df, list_year, function(x, y){
    x %>% left_join(y, by = join_by(FILE == FILE))
  })
  
  # combine
  df <- list_df %>% list_rbind()
  
  return(df)

  }
```



```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (ext inj)

save_df_surg_reg <- function(x){
  xlsx <- list.files(paste0("../xlsx/", x))

  from <- paste0("../xlsx/", x, "/", xlsx)
  
  df <- map(from, get_data_surg_reg) %>% list_rbind()

  return(df)
}
```

```{r}
save_df_surg_reg("surgery") %>% saveRDS("../rds/df_surg_dem_reg.RDS")
```



# add (additional cost)
# surgey do not have empty columns 
```{r}
get_data_surg_add <- function(xlsx_path){
  
  sheet_name <- getSheetNames(xlsx_path)
  
  sheet_name <- sheet_name[str_detect(sheet_name, "加算")]
  
  # read excel sheet
  list_df <- map2(xlsx_path,
                  sheet_name,
                  function(x, y) read.xlsx(x,
                                           sheet = y,
                                           startRow = 3,
                                           skipEmptyCols = FALSE,
                                           fillMergedCells = FALSE,
                                           cols = 1:8) %>%
                    return())


    # clean colnames
  new_colnames <- c("ADD",
                      "CLASS_code", "CLASS_name",
                       "PRO_code", "PRO_name",
                       "POINT", "PERC", "TOTAL")

  # update column names
  list_df <- map(list_df,
                 function(x){
                   colnames(x) <- new_colnames
                   return(x)})
  
    # clean colnames, remove white space
  list_df <- map(list_df,
                 function(x) x %>%
                   mutate(across(starts_with("CLASS"), ~ as.character(.x))) %>%
                   mutate(across(starts_with("CLASS"), ~ na_if(.x, " "))) %>%
                   return()
                 )


  
  # fill add first
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     tidyr::fill(starts_with("ADD"), .direction = "down")
                 })
  
  # split columns
  list_df_dev <- map(list_df,
                     function(x){
                       x %>% filter(ADD == "手術医療機器等加算") %>%
                         tidyr::fill(starts_with("CLASS"), .direction = "down") %>%
                         return()
                     })
  
  
  list_df_tc <- map(list_df,
                    function(x){
                      x %>% filter(ADD == "通則加算・注加算") 
                    })
  
  list_df <- map2(list_df_dev, 
                 list_df_tc, 
                 function(x, y){
                   x %>% bind_rows(y) %>% return()
  })
  
  
  # add file name

  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     mutate(FILE = xlsx_path) %>%
                     mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
                     relocate(FILE, .before = "ADD")  
                 })

  # add sheet name and do one hot coding for sheet
  # "注射薬 外来 (院内)" "注射薬 外来 (院外)" "注射薬 入院"  
  list_df <- map2(list_df, sheet_name,
                 function(x, y){
                   x %>% 
                     mutate(SHEET_jp = y) %>%
                         mutate(SHEET = case_when(
                           str_detect(SHEET_jp, "全体") ~ "all",
                           str_detect(SHEET_jp, "外来")　&
                             !str_detect(SHEET_jp, "加算")~ "out",
                           str_detect(SHEET_jp, "外来")　&
                             str_detect(SHEET_jp, "加算")~ "out_add",
                           str_detect(SHEET_jp, "入院") &
                             !str_detect(SHEET_jp, "加算") ~ "in",
                           str_detect(SHEET_jp, "入院") &
                             str_detect(SHEET_jp, "加算") ~ "in_add"))    %>%
                     relocate(SHEET, .after = "FILE")
                   })
  
  # fill missing cells
  
  list_df <- map(list_df,
                 function(x){
                   x %>% 
                     mutate(across(everything(), as.character))
                 })
  
  df <- list_df %>% list_rbind()
  
  return(df)

  }
```



```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (ext inj)

save_df_surg_add <- function(x){
  xlsx <- list.files(paste0("../xlsx/", x))

  from <- paste0("../xlsx/", x, "/", xlsx)
  
  df <- map(from, get_data_surg_add) %>% list_rbind()

  return(df)
}
```

```{r}
save_df_surg_add("surgery")  %>% saveRDS("../rds/df_surg_add.RDS")
```

